### ISSUE TITLE
carousel last page bug

### ISSUE THREAD

**Issue by leninlal** [METIT-BU/xblock-carousel#1]
This is what happens when i get to last image and select "next".
![unit unit carousel xblock edx studio](https://cloud.githubusercontent.com/assets/7258851/8371674/534a0a8a-1bf8-11e5-91be-e1b7315b9db8.png)

**Comment by con-yo** [comment]
Has anyone found a solution to this problem?  I see it in some implementations but not others. So am wondering whether there is a known fix.

**Comment by leninlal** [comment]
@con-yo 
i fixed this issue, you have to edit the responsive_carousel.js

**Comment by altahoo** [comment]
@leninlal I am working on integrating carousel xblock into edx now. Could you share the commit link for your fix if you have committed it? I did not find the fix in your repo or carousel repo. Or can you let me know what specific you edit in responsive_carousel.js? Thanks.

**Comment by leninlal** [comment]
@con-yo  Please replace the responsive_carousel.js file with this file
https://gist.github.com/leninlal/d6caa800cdc50608d768 . And let me know if it doesn't works.

**Comment by yuvarajbu** [comment]
I believe the responsive-carousel.js can edited to fix this problem. Git pull for new changes and lemme know if you still have this issue.
